### PR TITLE
Add Details To Arcadia Page

### PR DESCRIPTION
**Pull request by HysMagus**
Adding Details to Arcadia Page
I swear they're accurate!

### CODE REVIEW

**Comment by HysMagus** [comment]
Bumping this!

**Comment by devendran-m** [comment]
> Bumping this!

Hi @HysMagus , 

We can add the "Security" `Tag`; however, the `Segment` value should stay as "Software House", as it is an internal categorisation and required for analytics. Could you update the `Segment` value back to Software House please?
image

**Comment by HysMagus** [comment]
@devendran-m Done!

**Review by devendran-m — APPROVED** [review]
Thank you, The changes look good.

**Pull request merged**
