### PR TITLE
Update existing grants metadata and add new grant entries

### PR DESCRIPTION
**Pull request by devendran-m**
**What are the changes**
- Fix PM Name in Mlem Metadata
- Fix/Update Milestone details/dates for existing grant entries
- Update Grant Size to Small, Medium and Large
- Add new Grants to the list. Criterion for adding a Grant to the list - KYC / KYB Completed

**Change log**
```bash
        new file:   grants/artcoin/data.md
        new file:   grants/artcoin/m1.md
        modified:   grants/caspershops/data.md
        modified:   grants/caspershops/m1.md
        new file:   grants/caspershops/m2.md
        new file:   grants/caspershops/m3.md
        new file:   grants/caspershops/m4.md
        new file:   grants/cryptonaire/data.md
        new file:   grants/cryptonaire/m1.md
        modified:   grants/dappium/data.md
        modified:   grants/fondant/data.md
        modified:   grants/fondant/m1.md
        modified:   grants/gameswift/data.md
        new file:   grants/gbm_auctions/data.md
        new file:   grants/gbm_auctions/m1.md
        modified:   grants/minteandome/m2.md
        modified:   grants/mlem/data.md
        new file:   grants/mlem/m2.md
        modified:   grants/niftyrow/data.md
        modified:   grants/niftyrow/m1.md
        modified:   grants/profueltrace/data.md
        modified:   grants/profueltrace/m1.md
        modified:   grants/profueltrace/m2.md
        new file:   grants/simplewallet/data.md
        new file:   grants/simplewallet/m1.md
        new file:   grants/verso/data.md
        new file:   grants/verso/m1.md
        modified:   grants/xpnetwork/data.md
```

### CODE REVIEW

**Review by alejandro-blockbites — APPROVED** [review]
LGTM

**Comment by piotr-dziubecki** [comment]
I think this looks good to me. The naming for the grant sizes would be changed later on - as we discuss this with Steve D. For now let's promote this to prod.

**Review by piotr-dziubecki — APPROVED** [review]

**Comment by devendran-m** [comment]
Thanks @piotr-dziubecki, merging it now
cc: @alejandro-blockbites

**Comment by Marjan-sha** [comment]
For Mlem, both milestones are delivered an in review

**Comment by devendran-m** [comment]
> For Mlem, both milestones are delivered an in review

Thanks @Marjan-sha , I will update it via a new PR

**Pull request merged**
